=== nuddler/xml/bin/hurtownia.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.pkck.com" xmlns:tns="http://www.pkck.com"
	elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xs:simpleType name="typWersja">
		<xs:restriction base="xs:decimal">
			<xs:fractionDigits value="1" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="typAutor">
		<xs:sequence>
			<xs:element name="imię_autora" type="tns:typImię" minOccurs="1"
				maxOccurs="2" />
			<xs:element name="nazwisko_autora" type="xs:string" />
			<xs:element name="nr_indeksu" type="tns:typIndeks" />
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="typImię">
		<xs:restriction base="xs:string">
			<xs:maxLength value="20" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="typIndeks">
		<xs:restriction base="xs:unsignedInt">
			<xs:pattern value="[1-9][0-9]{5}" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="typKlient">
		<xs:sequence>
			<xs:element name="imię_klienta" type="xs:string"
				minOccurs="1" maxOccurs="2" />
			<xs:element name="nazwisko_klienta" type="xs:string" />
			<xs:element name="telefon" type="tns:typTelefon" />
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="typCena">
		<xs:restriction base="xs:decimal">
			<xs:fractionDigits value="2" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="typWaluta">
		<xs:restriction base="xs:string">
			<xs:enumeration value="PLN" />
			<xs:enumeration value="EUR" />
			<xs:enumeration value="USD" />
		</xs:restriction>
	</xs:simpleType>

	<xs:attributeGroup name="towarAtrybuty">
		<xs:attribute name="nazwa_towaru" type="xs:string" use="required" />
		<xs:attribute name="dział" type="xs:string" />
	</xs:attributeGroup>

	<xs:simpleType name="typTelefon">
		<xs:restriction base="xs:unsignedInt">
			<xs:pattern value="[1-9][0-9]{8}" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="typPłatność">
		<xs:attributeGroup ref="tns:typPłatnośćAtrybuty" />
	</xs:complexType>

	<xs:attributeGroup name="zamówienieAtrybuty">
		<xs:attribute name="id_zamówienia" type="xs:integer" use="required" />
		<xs:attribute name="towar" type="xs:string" />
	</xs:attributeGroup>

	<xs:attributeGroup name="typPłatnośćAtrybuty">
		<xs:attribute name="kanał" type="tns:typKanał" default="przelew" />
		<xs:attribute name="raty" type="tns:typRaty" default="nie" />
	</xs:attributeGroup>

	<xs:simpleType name="typKanał">
		<xs:restriction base="xs:string">
			<xs:enumeration value="przelew" />
			<xs:enumeration value="gotówka" />
			<xs:enumeration value="karta" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="typRaty">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="tak" />
			<xs:enumeration value="nie" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="hurtownia">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="autorzy">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="autor" type="tns:typAutor" minOccurs="0"
								maxOccurs="unbounded" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="działy">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="dział" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="opis_działu" type="xs:string"
											minOccurs="0" maxOccurs="1" />
									</xs:sequence>
									<xs:attribute name="nazwa_działu" type="xs:string"
										use="required" />
								</xs:complexType>

							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="towary">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="towar" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="cena">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="tns:typCena">
														<xs:attribute name="waluta" type="tns:typWaluta"
															default="PLN" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="opis_towaru" type="xs:string"
											minOccurs="0" maxOccurs="1" />
									</xs:sequence>

									<xs:attributeGroup ref="tns:towarAtrybuty" />
								</xs:complexType>

							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="zamówienia">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="zamówienie" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="klient" type="tns:typKlient" />
										<xs:element name="liczba_sztuk" type="xs:integer"/>
										<xs:element name="data_złożenia" type="xs:date" />
										<xs:element name="płatność" type="tns:typPłatność" />
									</xs:sequence>
									<xs:attributeGroup ref="tns:zamówienieAtrybuty" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="wersja" type="tns:typWersja" fixed="1.0" />
		</xs:complexType>
		
		<xs:keyref refer="tns:towar_key" name="zamówienieKeyRef">
			<xs:selector xpath="tns:zamówienia/tns:zamówienie" />
			<xs:field xpath="@towar" />
		</xs:keyref>
		
		<xs:key name="zamówienie_key">
			<xs:selector xpath="tns:zamówienia/tns:zamówienie" />
			<xs:field xpath="@id_zamówienia" />
		</xs:key>
		
		<xs:key name="dział_key">
			<xs:selector xpath="tns:działy/tns:dział" />
			<xs:field xpath="@nazwa_działu" />
		</xs:key>
		
		<xs:key name="towar_key">
			<xs:selector xpath="tns:towary/tns:towar" />
			<xs:field xpath="@nazwa_towaru" />
		</xs:key>
		
		<xs:keyref refer="tns:dział_key" name="działKeyRef">
			<xs:selector xpath="tns:towary/tns:towar"></xs:selector>
			<xs:field xpath="@dział"></xs:field>
		</xs:keyref>
	</xs:element>
</xs:schema>

=== nuddler/xml/src/hurtownia.xml
<?xml version="1.0" encoding="UTF-8"?>
<pkck:hurtownia wersja="1.0" 
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xmlns:pkck="http://www.pkck.com"
 xsi:schemaLocation="http://www.pkck.com hurtownia.xsd">

	 <pkck:autorzy>
		<pkck:autor>
			<pkck:imię_autora>Przemysław</pkck:imię_autora>
			<pkck:nazwisko_autora>Holak</pkck:nazwisko_autora>
			<pkck:nr_indeksu>180557</pkck:nr_indeksu>
		</pkck:autor>
		<pkck:autor>
			<pkck:imię_autora>Bartłomiej</pkck:imię_autora>
			<pkck:nazwisko_autora>Długosz</pkck:nazwisko_autora>
			<pkck:nr_indeksu>180525</pkck:nr_indeksu>
		</pkck:autor>
	</pkck:autorzy>

	<pkck:działy>
		<pkck:dział nazwa_działu="Elektronika">
			<pkck:opis_działu>Elementy elektroniczne</pkck:opis_działu>
		</pkck:dział>
		<pkck:dział nazwa_działu="Telefony">
			<pkck:opis_działu>Telefony komórkowe</pkck:opis_działu>
		</pkck:dział>
		<pkck:dział nazwa_działu="Biuro">
			<pkck:opis_działu>Papier etc.</pkck:opis_działu>
		</pkck:dział>
	</pkck:działy>
	
	
	<pkck:towary>
		<pkck:towar nazwa_towaru="Telefon1" dział="Elektronika">
			<pkck:cena>500.00</pkck:cena>
			<pkck:opis_towaru>Dobry telefon</pkck:opis_towaru>
		</pkck:towar>
		<pkck:towar nazwa_towaru="Telefon2" dział="Telefony">
			<pkck:cena>399.99</pkck:cena>
			<pkck:opis_towaru>Gorszy telefon</pkck:opis_towaru>
		</pkck:towar>
		<pkck:towar nazwa_towaru="GPS" dział="Elektronika">
			<pkck:cena>699.99</pkck:cena>
			<pkck:opis_towaru>Dobra nawigacja</pkck:opis_towaru>
		</pkck:towar>
		<pkck:towar nazwa_towaru="Tablet" dział="Elektronika">
			<pkck:cena>199.99</pkck:cena>
			<pkck:opis_towaru>Tani tablet</pkck:opis_towaru>
		</pkck:towar>
		<pkck:towar nazwa_towaru="Papier" dział="Biuro">
			<pkck:cena>15.99</pkck:cena>
			<pkck:opis_towaru>Najlepszy papier</pkck:opis_towaru>
		</pkck:towar>
		<pkck:towar nazwa_towaru="Spinacz" dział="Biuro">
			<pkck:cena waluta="USD">2.00</pkck:cena>
			<pkck:opis_towaru>Elegancki spinacz</pkck:opis_towaru>
		</pkck:towar>
	</pkck:towary>
	
	<pkck:zamówienia>
		<pkck:zamówienie id_zamówienia="ddd1" towar="GPS">
			<pkck:klient>
				<pkck:imię_klienta>Marcin</pkck:imię_klienta>
				<pkck:nazwisko_klienta>Trawka</pkck:nazwisko_klienta>
				<pkck:telefon>333333333</pkck:telefon>
			</pkck:klient>
			<pkck:liczba_sztuk>1</pkck:liczba_sztuk>
			<pkck:data_złożenia>2002-09-24</pkck:data_złożenia>
			<pkck:płatność kanał="gotówka" raty="nie"/>
		</pkck:zamówienie>
		<pkck:zamówienie id_zamówienia="2" towar="Tablet">
			<pkck:klient>
				<pkck:imię_klienta>Adam</pkck:imię_klienta>
				<pkck:nazwisko_klienta>Sprawka</pkck:nazwisko_klienta>
				<pkck:telefon>222222222</pkck:telefon>
			</pkck:klient>
			<pkck:liczba_sztuk>1</pkck:liczba_sztuk>
			<pkck:data_złożenia>2002-09-24</pkck:data_złożenia>
			<pkck:płatność kanał="przelew" raty="tak"/>
		</pkck:zamówienie>
		<pkck:zamówienie id_zamówienia="3" towar="Tablet">
			<pkck:klient>
				<pkck:imię_klienta>Przemysław</pkck:imię_klienta>
				<pkck:nazwisko_klienta>Długi</pkck:nazwisko_klienta>
				<pkck:telefon>999999999</pkck:telefon>
			</pkck:klient>
			<pkck:liczba_sztuk>2</pkck:liczba_sztuk>
			<pkck:data_złożenia>2002-09-24</pkck:data_złożenia>
			<pkck:płatność kanał="gotówka" raty="nie"/>
		</pkck:zamówienie>
		<pkck:zamówienie id_zamówienia="4" towar="Spinacz">
			<pkck:klient>
				<pkck:imię_klienta>Marian</pkck:imię_klienta>
				<pkck:nazwisko_klienta>Wojciechowski</pkck:nazwisko_klienta>
				<pkck:telefon>111111111</pkck:telefon>
			</pkck:klient>
			<pkck:liczba_sztuk>100</pkck:liczba_sztuk>
			<pkck:data_złożenia>2002-09-24</pkck:data_złożenia>
			<pkck:płatność kanał="gotówka" raty="nie"/>
		</pkck:zamówienie>
		<pkck:zamówienie id_zamówienia="5" towar="Spinacz">
			<pkck:klient>
				<pkck:imię_klienta>Łukasz</pkck:imię_klienta>
				<pkck:nazwisko_klienta>Kluchowski</pkck:nazwisko_klienta>
				<pkck:telefon>111112111</pkck:telefon>
			</pkck:klient>
			<pkck:liczba_sztuk>60</pkck:liczba_sztuk>
			<pkck:data_złożenia>2002-09-21</pkck:data_złożenia>
			<pkck:płatność kanał="gotówka" raty="nie"/>
		</pkck:zamówienie>
		<pkck:zamówienie id_zamówienia="6" towar="Papier">
			<pkck:klient>
				<pkck:imię_klienta>Sebastian</pkck:imię_klienta>
				<pkck:nazwisko_klienta>Kępa</pkck:nazwisko_klienta>
				<pkck:telefon>111111114</pkck:telefon>
			</pkck:klient>
			<pkck:liczba_sztuk>40</pkck:liczba_sztuk>
			<pkck:data_złożenia>2002-07-24</pkck:data_złożenia>
			<pkck:płatność kanał="gotówka" raty="nie"/>
		</pkck:zamówienie>
		<pkck:zamówienie id_zamówienia="7" towar="GPS">
			<pkck:klient>
				<pkck:imię_klienta>Robert</pkck:imię_klienta>
				<pkck:nazwisko_klienta>Mielczarski</pkck:nazwisko_klienta>
				<pkck:telefon>811111111</pkck:telefon>
			</pkck:klient>
			<pkck:liczba_sztuk>1</pkck:liczba_sztuk>
			<pkck:data_złożenia>2014-09-24</pkck:data_złożenia>
			<pkck:płatność kanał="gotówka" raty="nie"/>
		</pkck:zamówienie>
	</pkck:zamówienia>
</pkck:hurtownia>
